CPP = g++
PFLAGS = -Wall

OBJ1 = p2.1.o 
OBJ2 = p2.2.o 
OBJ3T = testWindGauge.o 
OBH3M = WindGauge.o
OBJ4 = p2.4.o 
OBJ5 = p2.5.o
OBJ6 = p2.5.o

all: main1	main2	main3	main4	main5	main6

main1: $(OBJ1) 
		$(CPP) $(PFLAGS) -o problem1 $(OBJ1) 

main2: $(OBJ2)
		$(CPP) $(PFLAGS) -o problem2 $(OBJ2)

main3: $(OBJ3T) $(OBH3M)
		$(CPP) $(PFLAGS) -o problem3 $(OBH3M) $(OBJ3T)
		
main4: $(OBJ4)
		$(CPP) $(PFLAGS) -o problem4 $(OBJ4) 

main5: $(OBJ5) 
		$(CPP) $(PFLAGS) -o problem5 $(OBJ5) 

main6: $(OBJ6) 
		$(CPP) $(PFLAGS) -o problem6 $(OBJ6) 

p2.1.o : p2.1.cpp
	$(CPP) $(PFLAGS) -c p2.1.cpp

p2.2.o : p2.2.cpp
	$(CPP) $(PFLAGS) -c p2.2.cpp

WindGauge.o : WindGauge.h WindGauge.cpp
	$(CPP) $(PFLAGS) -c WindGauge.cpp

testWindGauge.o : WindGauge.h testWindGauge.cpp
	$(CPP) $(PFLAGS) -c testWindGauge.cpp

p2.4.o : p2.4.cpp
	$(CPP) $(PFLAGS) -c p2.4.cpp

p2.5.o : p2.5.cpp
	$(CPP) $(PFLAGS) -c p2.5.cpp

p2.6.o : p2.6.cpp
	$(CPP) $(PFLAGS) -c p2.6.cpp
	
compileonly: $(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4) $(OBJ5) $(OBJ6)

deleteofiles:
	del -f *.o
	
deleteexec:
	del -f *.exe	

deleteall: deleteexec deleteofiles

