CPP = g++
PFLAGS = -Wall

OBJ1 = p1.1.o 
OBJ2 = testStack.o 
OBJ3 = testLinkedList.o 
OBJ4 = p1.4.o 
OBJ5 = p1.5.o

all: main1	main2	main3	main4	main5

main1: $(OBJ1) 
		$(CPP) $(PFLAGS) -o problem1 $(OBJ1) 

main2: $(OBJ2)
		$(CPP) $(PFLAGS) -o problem2 $(OBJ2)

main3: $(OBJ3)
		$(CPP) $(PFLAGS) -o problem3 $(OBJ3) 
		
main4: $(OBJ4)
		$(CPP) $(PFLAGS) -o problem4 $(OBJ4) 

main5: $(OBJ5) 
		$(CPP) $(PFLAGS) -o problem5 $(OBJ5) 

p1.1.o : p1.1.cpp
	$(CPP) $(PFLAGS) -c p1.1.cpp

testStack.o : testStack.cpp
	$(CPP) $(PFLAGS) -c testStack.cpp

testLinkedList.o : testLinkedList.cpp
	$(CPP) $(PFLAGS) -c testLinkedList.cpp

p1.4.o : p1.4.cpp
	$(CPP) $(PFLAGS) -c p1.4.cpp

p1.5.o : p1.5.cpp
	$(CPP) $(PFLAGS) -c p1.5.cpp
	
compileonly: $(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4) $(OBJ5)

deleteofiles:
	del -f *.o
	
deleteexec:
	del -f *.exe	

deleteall: deleteexec deleteofiles

